name = "Lumo Optimized"
author = "Luca Silverentand"
version = "1.1.0"
description = "A performance-focused Fabric modpack for Minecraft 1.21.8 optimized for low-end devices, integrated graphics, and older hardware."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c85f525f17e4ba778484a55586faaf7635f7e79841443cc16ae5673908f02ab"

[versions]
fabric = "0.19.5"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7"]
